model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: artefacts/model_checkpoints
  filename: null
  monitor: null
  save_top_k: -1
  mode: min
  verbose: true
  save_last: true
